name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: xdebug

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run Rector dry run
        run: ./vendor/bin/rector process src --dry-run

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse

      - name: Tests
        env:
          HATENA_ID: ${{ secrets.HATENA_ID }}
          HATENA_BLOG_ID: ${{ secrets.HATENA_BLOG_ID }}
          HATENA_API_KEY: ${{ secrets.HATENA_API_KEY }}
        run: ./vendor/bin/pest --coverage-clover=clover.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./clover.xml
          fail_ci_if_error: true